apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-website
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pet-website
    spec:
      containers:
        - name: pet-website
          image: REPLACE_WITH_REGISTRY

          ports:
            - containerPort: 3000
          resources:
            requests: 
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"