name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Minikube (for testing)
        uses: medyagh/setup-minikube@master

      - name: Build Docker image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t pet-website:latest .

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl rollout status deployment/pet-website --timeout=90s